### ISSUE TITLE
Calling my twilio number after completing the steps

### ISSUE THREAD

**Issue by corbinyo** [philnash/twitter-sms#3]
After calling my twilio number after completing the steps I get an error recording. as well these errors:

HTTP Requests                                                                   
-------------                                                                   
                                                                                
POST /voice/                   404 Not Found

**Comment by philnash** [comment]
Hey Corbin, I believe you emailed with a slightly different problem, which I've responded to. I'll close this for now, but do open it if you get this 404 again.
